export const localImages = {
    logo: require("../public/logo/elephant.png"),
    sliderOne: require("../public/slider/slider1.svg"),
    sliderTwo: require("../public/slider/slider2.svg"),
    sliderThree: require("../public/slider/slider3.svg"),
    showcaseOne: require("../public/showcase/aideoa.png"),
    showcaseTwo: require("../public/showcase/hmf.png"),
    showcaseThree: require("../public/showcase/tlhc.png"),
    teamOne: require("../public/team/dummy img.webp"),
    teamTwo: require("../public/team/dummy img.webp"),
    teamThree: require("../public/team/dummy img.webp"),
    teamFour: require("../public/team/team4.jpg"),
    contactUs: require("../public/contact/contact.svg"),
    visionOne: require("../public/vision/vision1.jpeg"),
    visionTwo: require("../public/vision/vision2.jpg"),
};
